---
prices:
  -
    code: ebooks
    name: "HTML & Ebook"
    description:
      |
        * Optimized for computer screens, Kindle, and iPad
        * Incredibly awesome content
    media:
      - ebooks
    price: 3500

  -
    code: all
    name: "HTML, Ebook, and Screencasts"
    description:
      |
        * Includes 10 hours of video screencasts
        * Ebooks inclded in PDF/EPUB/MOBI formats
    media:
      - ebooks
      - media/screencasts
    price: 12500

authors:
  -
    name: "Aleksey Tsalolikhin"
    image: /images/atsaloli.jpg
    contact_email: "aleksey@verticalsysadmin.com"
    contact_twitter: "@atsaloli"
    contact_fb: "http://facebook.com/atsaloli"
    contact_gh: "@atsaloli"
    bio:
      |
        Author bio [link](https://www.verticalsysadmin.com)

faq:
  -
    question: "What is CFEngine?"
    answer: "CFEngine is a tool for automating system administration so you can have a reliable IT infrastructure."

  -
    question: "Why should I use CFEngine?"
    answer: "CFEngine is based on Promise Theory, which is a way of modeling distributed systems as composed of autonomous agents engaged in voluntary cooperation. Promise Theory tells us that distributed decentralized systems can work at scales beyond strongly centralized systems. CFEngine is small, fast and secure. Many world class companies trust their IT infrastructures to CFEngine."

testimonials:
  -
    name: "Paul Reemeijer"
    title: "System Administrator at SURFsara"
    image: /images/paul_reemeijer.png
    text: "It is a VERY practical book. I love the way you give examples and the flow of the chapters. It gives me a good feeling of what you can do with CFEngine."
  -
    name: "Stanislav Yotov"
    title: "Statistician / Data Scientist at Cloudwick"
    image: /images/stanislav_yotov.png
    text: "I am learning CFEngine and I would like to express my gratitude for the tutorials. They are amazing and extremely useful for me to start getting a grasp of CFEngine's capabilities."



marketing_content: ''

repo_url: ''
contact_email: ''
hide_custom_domain_footer: false
